### PR TITLE
fix compilation type error on Xcode 9

### PR DESCRIPTION
**Pull request by tsheaff**

### CODE REVIEW

**Comment by tsheaff** [comment]
@zoul would be nice to get out a 1.0.1 with this guy, until then my podfile has to point at my calm/Finch fork.

**Comment by shockdesign** [comment]
@tsheaff You shouldn't need to reimport OpenAL.. demo and library seem to build fine after fixing the compilation type error on Xcode 9..

**Comment by tsheaff** [comment]
Didn't for me, I had to add that line back to get things working... Not sure what's different about our setups.

**Comment by shockdesign** [comment]
@tsheaff Not sure whats different either, except I just tried this today with the release of Xcode 9..

**Pull request closed without merging**
